### ISSUE TITLE
device becomes unresponsive once screen is locked

### ISSUE THREAD

**Issue by y08wilm** [y08wilm/a7-ios7-downgrader#1]

**Comment by LunarN0v4** [comment]
after some research (aka @y08wilm talking to a friend), we've found out that this issue cannot be fixed.  
the issue is that old devices will fallback to securerom when it does a "deep sleep", then going through an order of sec rom, llb, iboot, then userland, but since there's no signed llb on the disk, the device will become unresponsive (die)  
this issue cannot and will not be fixed.
